// SPDX-License-Identifier: MPL-2.0
import { connectToShellCanvas, RpcError, type Json } from "@techartdev/shellcanvas-app-sdk";
import { nextOffset } from "./paging.js";

type Cell={kind:string;display:string}; type Column={name:string;databaseType:string};
type Page={resultId:string;columns:Column[];rows:Cell[][];offset:number;totalRows:number;hasMore:boolean;truncated:boolean;affectedRows:number;warnings:string[]};
type Table={name:string;kind:string};
const S="dev.shellcanvas.database";
const root=document.querySelector<HTMLDivElement>("#root")!;
root.innerHTML=`<main><header><div><p class="eyebrow">SHELLCANVAS DATABASE</p><h1>Query workspace</h1></div><span id="provider">Connecting…</span></header><div class="notice">SQL runs with the configured database account's privileges. Review statements before running them.</div><section class="workspace"><aside><div class="side-head"><strong>Schema</strong><button id="reload" title="Reload schemas" disabled>↻</button></div><div id="tree"></div></aside><div class="work"><label for="sql">SQL query</label><textarea id="sql" spellcheck="false" placeholder="SELECT …"></textarea><div class="toolbar"><button id="run" class="primary" disabled>Run query</button><button id="cancel" disabled>Cancel</button><span id="status" role="status">Connecting…</span></div><div id="warnings"></div><div class="result-head"><strong id="summary">No result</strong><div><label class="safe"><input id="safe" type="checkbox" checked> Spreadsheet-safe CSV</label><button id="export" disabled>Save CSV…</button></div></div><div class="grid-wrap"><table><thead></thead><tbody></tbody></table><div id="empty">Run a query to see results.</div></div><div class="pager"><button id="prev" disabled>Previous</button><span id="page"></span><button id="next" disabled>Next</button></div></div></section></main>`;
const $=<T extends HTMLElement>(id:string)=>document.querySelector<T>(`#${id}`)!;
const sql=$("sql") as HTMLTextAreaElement,status=$("status"),run=$("run") as HTMLButtonElement,cancel=$("cancel") as HTMLButtonElement,exportButton=$("export") as HTMLButtonElement;
let client:Awaited<ReturnType<typeof connectToShellCanvas>>,current:Page|null=null,controller:AbortController|null=null,provider="",pageSize=100,binding:string|null=null,generation=0,schemaOp=0,pageOp=0,bindOp=0,exportJob:string|null=null,pageBusy=false,ready=false,previousOffsets:number[]=[];
function message(error:unknown){status.textContent=error instanceof RpcError?`${error.code}: ${error.message}`:error instanceof Error?error.message:String(error)}
async function call<T>(method:string,params:Json={},signal?:AbortSignal):Promise<T>{return await client.services.call(`${S}.${method}`,params,signal) as unknown as T}
function quote(name:string){return provider==="mysql"?`\`${name.replaceAll("`","``")}\``:`"${name.replaceAll('"','""')}"`}
function tableSql(schema:string,table:string){const full=provider==="sqlite"?quote(table):`${quote(schema)}.${quote(table)}`;return provider==="sqlserver"?`SELECT TOP (200) * FROM ${full};`:`SELECT * FROM ${full} LIMIT 200;`}
function render(page:Page){current=page;const head=document.querySelector("thead")!,body=document.querySelector("tbody")!;head.replaceChildren();body.replaceChildren();
  if(page.columns.length){const tr=document.createElement("tr");for(const c of page.columns){const th=document.createElement("th");th.textContent=c.name;th.title=c.databaseType;tr.append(th)}head.append(tr)}
  for(const row of page.rows){const tr=document.createElement("tr");for(const cell of row){const td=document.createElement("td");td.textContent=cell.kind==="null"?"NULL":cell.display;td.className=`cell-${cell.kind}`;td.title=cell.kind;tr.append(td)}body.append(tr)}
  $("empty").hidden=page.columns.length>0||page.rows.length>0;$("summary").textContent=`${page.totalRows.toLocaleString()} row${page.totalRows===1?"":"s"}${page.truncated?" (limit reached)":""}`;$("page").textContent=page.totalRows?`${page.offset+1}–${Math.min(page.offset+page.rows.length,page.totalRows)} of ${page.totalRows}`:"";
  ($("prev") as HTMLButtonElement).disabled=page.offset===0;($("next") as HTMLButtonElement).disabled=!page.hasMore;exportButton.disabled=!page.columns.length;$("warnings").textContent=page.warnings.join(" · ");
}
function clearResult(note:string,close=true){const old=current;current=null;if(close&&old&&client)void call("closeResult",{resultId:old.resultId,offset:0,pageSize:1}).catch(()=>{});document.querySelector("thead")!.replaceChildren();document.querySelector("tbody")!.replaceChildren();$("summary").textContent=note;$("page").textContent="";$("warnings").textContent="";$("empty").hidden=false;exportButton.disabled=true;($("prev") as HTMLButtonElement).disabled=true;($("next") as HTMLButtonElement).disabled=true}
async function loadSchemas(){const op=++schemaOp,gen=generation,tree=$("tree");tree.textContent="Loading…";try{const value=await call<{schemas:string[]}>("schemas");if(op!==schemaOp||gen!==generation)return;tree.replaceChildren();for(const schema of value.schemas){const details=document.createElement("details"),summary=document.createElement("summary");summary.textContent=schema;details.append(summary);details.addEventListener("toggle",()=>{if(details.open&&details.childElementCount===1)void loadTables(details,schema,gen)});tree.append(details)}if(!value.schemas.length)tree.textContent="No schemas visible."}catch(e){if(op!==schemaOp||gen!==generation)return;tree.textContent="Could not load schemas.";message(e)}}
async function loadTables(details:HTMLDetailsElement,schema:string,gen:number){const wait=document.createElement("p");wait.textContent="Loading…";details.append(wait);try{const value=await call<{tables:Table[]}>("tables",{schema});if(gen!==generation||!details.isConnected)return;wait.remove();for(const table of value.tables){const button=document.createElement("button");button.className="table";button.textContent=table.name;button.title=`${table.kind} — insert a query template`;button.onclick=()=>{sql.value=tableSql(schema,table.name);sql.focus()};details.append(button)}if(!value.tables.length){wait.textContent="Empty";details.append(wait)}}catch(e){if(gen!==generation||!details.isConnected)return;wait.textContent="Could not load tables";message(e)}}
async function execute(){if(controller||!ready)return;const gen=generation,active=new AbortController();controller=active;run.disabled=true;cancel.disabled=false;clearResult("Running query…");previousOffsets=[];status.textContent="Running…";try{const page=await client.services.call(`${S}.query`,{sql:sql.value,pageSize},active.signal) as unknown as Page;if(gen!==generation)return;render(page);status.textContent="Query finished."}catch(e){if(gen===generation){clearResult("Query failed");message(e)}}finally{if(controller===active)controller=null;if(gen===generation&&ready){run.disabled=false;cancel.disabled=true}}}
async function move(offset:number,remember?:number){if(!current||pageBusy)return false;const op=++pageOp,gen=generation,resultId=current.resultId;pageBusy=true;try{const page=await call<Page>("page",{resultId,offset,pageSize});if(op===pageOp&&gen===generation&&current?.resultId===resultId){if(remember!==undefined)previousOffsets.push(remember);render(page);return true}}catch(e){if(op===pageOp&&gen===generation)message(e)}finally{if(op===pageOp){pageBusy=false}}return false}
async function previous(){const offset=previousOffsets.pop();if(offset===undefined)return;if(!await move(offset))previousOffsets.push(offset)}
async function cancelExport(){const job=exportJob;exportJob=null;if(job)await call("exportCancel",{jobId:job}).catch(()=>{})}
async function exportCsv(){if(!current||exportJob)return;const gen=generation;exportButton.disabled=true;status.textContent="Choose a CSV destination…";try{const start=await call<{jobId:string}>("exportBegin",{resultId:current.resultId,suggestedName:"query-results.csv",spreadsheetSafe:($("safe") as HTMLInputElement).checked});if(gen!==generation){await call("exportCancel",{jobId:start.jobId}).catch(()=>{});return}exportJob=start.jobId;for(let polls=0;polls<180&&exportJob===start.jobId;polls++){await new Promise(r=>setTimeout(r,350));const job=await call<{state:string;name?:string;message?:string}>("exportStatus",{jobId:start.jobId});if(gen!==generation){await cancelExport();return}if(job.state==="saved"){status.textContent=`Saved ${job.name??"CSV"}.`;exportJob=null;return}if(job.state==="canceled"){status.textContent="CSV save canceled.";exportJob=null;return}if(job.state==="failed")throw new Error(job.message??"CSV export failed");if(job.state!=="choosing"&&job.state!=="writing")throw new Error("Adapter returned an unknown export state")}await cancelExport();throw new Error("CSV save timed out") }catch(e){await cancelExport();if(gen===generation)message(e)}finally{exportButton.disabled=!current?.columns.length}}
const required=["capabilities","schemas","tables","columns","query","page","closeResult","exportBegin","exportStatus","exportCancel"].map(v=>`${S}.${v}`);
async function bind(){const op=++bindOp,env=await client.environment.get();if(op!==bindOp||env.binding===binding)return;generation++;schemaOp++;pageOp++;pageBusy=false;previousOffsets=[];ready=false;controller?.abort();controller=null;run.disabled=true;cancel.disabled=true;($("reload") as HTMLButtonElement).disabled=true;await cancelExport();if(op!==bindOp)return;binding=env.binding;clearResult("Run a query to see results.");const methods=await client.services.list();if(op!==bindOp)return;if(!required.every(name=>methods.some(m=>m.name===name&&m.available&&m.granted)))throw new Error("This app needs the Database adapter and all database service permissions.");const info=await call<{provider:string}>("capabilities");if(op!==bindOp)return;provider=info.provider;$("provider").textContent=provider;ready=true;run.disabled=false;($("reload") as HTMLButtonElement).disabled=false;status.textContent="Ready.";await loadSchemas()}
async function start(){client=await connectToShellCanvas();await bind();client.events.subscribe(()=>{void bind().catch(message)},message);window.addEventListener("pagehide",()=>{generation++;controller?.abort();void cancelExport();client.dispose()},{once:true})}
run.onclick=()=>void execute();cancel.onclick=()=>controller?.abort();$("reload").onclick=()=>void loadSchemas();$("prev").onclick=()=>void previous();$("next").onclick=()=>{if(current)void move(nextOffset(current),current.offset)};exportButton.onclick=()=>void exportCsv();sql.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"&&ready){e.preventDefault();void execute()}});void start().catch(message);
